### PR TITLE
add hssp as just for fun project

### PR DESCRIPTION
**Pull request by sterchelen**
If you are fixing typos or correcting grammar, thanks!

If you are proposing a new section be added to the page,
be aware I may not accept it. Best if you open
[an issue](https://github.com/seven1m/justforfunnoreally.dev/issues)
to discuss your proposal first.

And last, if you are adding your project to the table
at the bottom of the page, make *sure* you are following
the pattern and instructions:

1. No distasteful projects! Anything adult in nature--
   meaning anything I would even-so-much-as hesitate to
   describe to my 6-year-old niece--
   is strictly forbidden.

2. Add your project to the **bottom** of the table.
   For now, there is no sorting. I may choose to sort
   the table alphabetically or in any order I wish in
   the future.
  
3. Only link to the **source code repository** for your
   project, e.g. GitHub, GitLab, Bitbucket, sr.ht, etc.
   You may **not** link to a project website, sorry.

4. In the description for your project, be sure to write
   it like this:
   
   > a Ruby Compiler, for fun

   - The first word must be the article "a" or "an".
   - The next 2-5 words is a description of your project.
   - Next, you must follow with a comma (,) and the words
     "for fun", as above.

### CODE REVIEW

**Comment by sterchelen** [comment]
ping @seven1m :)

**Comment by seven1m** [comment]
Oh sorry, I saw this awhile back, but noticed the description was quite long. Can you shorten it to 5 words or less? These things tend to get longer and longer. 😅

**Comment by sterchelen** [comment]
> Oh sorry, I saw this awhile back, but noticed the description was quite long. Can you shorten it to 5 words or less? These things tend to get longer and longer. sweat_smile
> 
> I.e. "a, [5 words], for fun"

Sure, fixed ✅

**Comment by seven1m** [comment]
Thanks!

**Pull request merged**
